# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0013_auto_20160105_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscourseProjectThread',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('post_id', models.PositiveIntegerField()),
            ],
        ),
    ]
