# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ore.core.util


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationteam',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[\\w.\\-_]+$', 'Enter a valid team name.', 'invalid'), ore.core.util.validate_not_prohibited], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[\\w.\\-_]+$', 'Enter a valid team name.', 'invalid'), ore.core.util.validate_not_prohibited], verbose_name='name'),
        ),
    ]
