# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_oreuser_external_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='oreuser',
            managers=[
            ],
        ),
    ]
