# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 16:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0005_auto_20160213_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-ordering_id']},
        ),
        migrations.AddField(
            model_name='file',
            name='plugin_dependencies',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='file',
            name='plugin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
