# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ore.core.util


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='hex',
            field=models.CharField(max_length=6, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Try to sum your plugin up in 140 characters or less.', verbose_name='Tagline (optional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[\\w.\\-_]+$', 'Enter a valid project name.', 'invalid'), ore.core.util.validate_not_prohibited], verbose_name='name'),
        ),
    ]
